name: PublishStaging

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v8.0.12
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: 'Package Json'
      #   run: cat ./package.json

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: YARN Install
        run: yarn install
        env:
          DEFAULT_BRANCH: release

      - name: YARN Build        
        run: yarn build
        env:
          DEFAULT_BRANCH: release

      - name: YARN Publish 
        run: yarn publish
        env:
          DEFAULT_BRANCH: release
